### ISSUE TITLE
[TlsInterception] `OSError` when sending empty chunk to clients under `Python < 3.10`

### ISSUE THREAD

**Issue by softhub-software-development** [abhinavsingh/proxy.py#978]
So far I used `proxy.py` version `2.3.1` to develop a plugin. Since I switched to version `2.4.0rc2`, I am getting the following
info/warning messages and TLS based access is denied. I tried with `rc5` which issues the same messages on both the
Windows and macOS platform.

```
2022-01-11 15:13:15,840 - pid:1575 [W] handler.handle_readables:266 - Exception when receiving from client connection#29 with reason FileNotFoundError(2, 'No such file or directory')
2022-01-11 15:13:15,840 - pid:1576 [W] handler.handle_readables:266 - Exception when receiving from client connection#29 with reason FileNotFoundError(2, 'No such file or directory')
2022-01-11 15:13:15,840 - pid:1575 [I] server.access_log:406 - 127.0.0.1:50398 - CONNECT clientservices.googleapis.com:443 - 0 bytes - 50.59ms
2022-01-11 15:13:15,841 - pid:1576 [I] server.access_log:406 - 127.0.0.1:50400 - CONNECT accounts.google.com:443 - 0 bytes - 45.82ms
2022-01-11 15:13:16,290 - pid:1576 [W] handler.handle_readables:266 - Exception when receiving from client connection#29 with reason FileNotFoundError(2, 'No such file or directory')
2022-01-11 15:13:16,291 - pid:1576 [I] server.access_log:406 - 127.0.0.1:50404 - CONNECT www.google.com:443 - 0 bytes - 44.86ms
```

The browser states "The website is not reachable" and shows `ERR_CONNECTION_CLOSED` as the error message.

To my best knowledge, both configurations, `v2.3.1` and `2.4.0rcX `are using the same configuration and use the same
certificates but only `v2.3.1` works. I am using `Python 3.9`.

I also notice that there are no cached server certificates in `~/.proxy/certificates` when using `2.4.0rcX`.

**Comment by abhinavsingh** [comment]
Thank you for reporting this.  Let's dig deep.  Can you also share the flags you are passing to  the proxy instance.

**Comment by softhub-software-development** [comment]
Hi,

I am using this little main.py to start up with the flags below. I just hope I do not screw anything up by setting sys.argv.

import proxy
import sys

if __name__ == '__main__':
    sys_argv = [
        'proxy.py',
        '--plugins', 'proxy.plugin.LocalDownloadPlugin',
        '--hostname', '127.0.0.1',
        '--port', '8899',
        '--ca-key-file', 'ca-key.pem',
        '--ca-cert-file', 'ca-cert.pem',
        '--ca-signing-key-file', 'ca-signing-key.pem'
    ]
    sys.argv = sys_argv
    proxy.entry_point()

**Comment by abhinavsingh** [comment]
Thank you, I believe the reason we see `No such file or directory` is because certificate generation is failing for some reason when using `v2.4.0` series.  I may have to look into it.  I used TLS interception last week, but certificates I have are trusted on the system.

Also, whenever you change CA certificates, you must delete `~/.proxy/certificates`, otherwise, again you can run into similar issues.  In, `v2.4.0` we also changed how certificate serial number is generated.

To double check, can you

1. delete `~/.proxy/certificates`
2. try again with `v2.4.0`

Also

1. delete `~/.proxy/certificates`
2. Trust generated root CA on system
3. try again with `v2.4.0`

**Comment by abhinavsingh** [comment]
I also remember us changing default minimum SSL/TLS versions.  Even that could have an impact here.  But let's double check suggested workflows and then proceed to next step of investigation.  Thank you.

**Comment by softhub-software-development** [comment]
> To double check, can you
> 
> 1. delete `~/.proxy/certificates`
> 2. try again with `v2.4.0`
> 

The folder ~/.proxy/certificates stays empty and accessing i.e. www.google.com results in "www.google.com
has closed the connection unexpectedly"

> Also
> 
> 1. delete `~/.proxy/certificates`
> 2. Trust generated root CA on system
> 3. try again with `v2.4.0`

I ran "make ca-certificates" again, result is same as above. No new certificates in the cache at ~/.proxy/certificates.

**Comment by abhinavsingh** [comment]
Thank you again for highlighting this issue.  I should try to delete my old certificates, un-trust them from system and try again.   Looks like for some reason same workflow broken in `2.4.x` series while it still works today in `2.3.x` series.

We must also add an integration test for interception so that it is never found broken again.  We only have unit tests, which assumes certificate generation works :(

**Comment by abhinavsingh** [comment]
I tried here with latest develop branch, and seems to work, see logs here

https://github.com/abhinavsingh/proxy.py/pull/979#issuecomment-1012032316

**Comment by softhub-software-development** [comment]
> I tried here with latest develop branch, and seems to work, see logs here
> 
> [#979 (comment)](https://github.com/abhinavsingh/proxy.py/pull/979#issuecomment-1012032316)

I switched to the development branch and tried with Branch_5b5c77ed. (#968) and I get an error on launch:
File "...\Python39\lib\selectors.py", line 315, in _select r, w, x = select.select(r, w, w, timeout)
OSError> [WinError 10022] Invalid argument

**Comment by abhinavsingh** [comment]
Can you try again with `--threaded` flag.  `Threadless` is disabled on windows but looks like it still is going in threadless mode.

Also does it work on Mac?  I am on Mac and haven't had a chance to try it elsewhere.

**Comment by abhinavsingh** [comment]
> OSError> [WinError 10022] Invalid argument

This is similar to https://github.com/abhinavsingh/proxy.py/issues/492

**Comment by abhinavsingh** [comment]
PR has submitted, which marked this issue as closed . Thanks for reporting it again.

Next we'll add integration tests for TLS interception, so that this never breaks again unexpected.

TLS Interception should work on Mac and Linux by default.  It should work on Windows under threaded mode.  Please re-open if this is not the case.  Use develop branch, we'll shortly release new release candidate.

**Comment by softhub-software-development** [comment]
> Can you try again with `--threaded` flag. `Threadless` is disabled on windows but looks like it still is going in threadless mode.
> 
> Also does it work on Mac? I am on Mac and haven't had a chance to try it elsewhere.

--threaded didn't help, same error as before. On the Mac, 2.4.0.rc6 does not throw the exception in selectors.py but shows the FileNotFoundError(2, 'No such file...') message like reported for 2.4.0rc2 on Windows.

**Comment by abhinavsingh** [comment]
> On the Mac, 2.4.0.rc6 does not throw the exception in selectors.py but shows the FileNotFoundError(2, 'No such file...') message like reported for 2.4.0rc2 on Windows.

Not `rc6`, can you try with develop on `MacOS`?

**Comment by abhinavsingh** [comment]
> I am at "Type fixes (#979)", on the develop branch, a little ahead of rc6. So that should be ok.

Yes this is ok, but then again thats weird.  I just gave it a try on Mac locally (12.0.1) and works as mentioned in https://github.com/abhinavsingh/proxy.py/pull/979#issuecomment-1012032316

**Comment by softhub-software-development** [comment]
I started from scratch again on macOS; hope I have made all the fine tunings; I am using Python 3.9.9 and PyCharm.

Here is how I start the proxy (main.py):

import proxy
import sys

if __name__ == '__main__':
    sys.flags = [
        'proxy',      # still without TLS; no certificates here
    ]
    proxy.entry_point()

Here is the stack trace:

2022-01-13 16:59:17,764 - pid:2257 [I] plugins.load:85 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2022-01-13 16:59:17,765 - pid:2257 [I] listener.setup:97 - Listening on 127.0.0.1:8899
Traceback (most recent call last):
  File "/Users/chris/Documents/pysrc/proxy.py/main.py", line 9, in <module>
    proxy.entry_point()
  File "/Users/chris/Documents/pysrc/proxy.py/proxy/proxy.py", line 267, in entry_point
    main()
  File "/Users/chris/Documents/pysrc/proxy.py/proxy/proxy.py", line 262, in main
    with Proxy(sys.argv[1:], **opts):
  File "/Users/chris/Documents/pysrc/proxy.py/proxy/proxy.py", line 140, in __enter__
    self.setup()
  File "/Users/chris/Documents/pysrc/proxy.py/proxy/proxy.py", line 195, in setup
    self.acceptors.setup()
  File "/Users/chris/Documents/pysrc/proxy.py/proxy/core/acceptor/pool.py", line 100, in setup
    self._start()
  File "/Users/chris/Documents/pysrc/proxy.py/proxy/core/acceptor/pool.py", line 145, in _start
    acceptor.start()
  File "/Users/chris/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/chris/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/chris/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/context.py", line 283, in _Popen
    from .popen_spawn_posix import Popen
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1349, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1321, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1453, in find_spec
  File "<frozen importlib._bootstrap_external>", line 38, in _relax_case
AttributeError: 'list' object has no attribute 'ignore_environment'

Process finished with exit code 1

Hope I didn't omit any step in the setup.

**Comment by abhinavsingh** [comment]
That is certainly not correct.  See

- https://github.com/abhinavsingh/proxy.py#blocking-mode
- https://github.com/abhinavsingh/proxy.py#non-blocking-mode

**Comment by abhinavsingh** [comment]
@softhub-software-development Also see https://github.com/abhinavsingh/proxy.py/issues/985

**Comment by softhub-software-development** [comment]
Embedding using proxy.main(...) worked with 2.3.1 but in 2.4.0rcX I get an error message:
TypeError: main() takes 0 positional arguments but 1 was given

```
  proxy.main([
    '--hostname', '::1',
    '--port', '8899'
  ])
```

**Comment by abhinavsingh** [comment]
Current, `proxy.main` now picks up on `sys.args` automatically.  You need not pass them as list.  Instead you can use kwargs like:

`main(hostname=ipaddress.IPAddress('127.0.0.1), port=8899)`

Read code when in doubt :). I will update the doc soon. Can't recall why this behavior was changed.

<img width="415" alt="Screen Shot 2022-01-14 at 2 14 24 PM" src="https://user-images.githubusercontent.com/126065/149484008-9e2e12d0-6564-4ad3-9177-db6763c30006.png">

**Comment by abhinavsingh** [comment]
I have re-opened this issue, because there indeed is a bug for Python < 3.10.   I use 3.10 locally and hence never caught it.  Looks like sending empty string to client will result in `OSError`.  This wasn't the case earlier, but is now.  This still is not the case in 3.10 yet.

Anyways

- https://github.com/abhinavsingh/proxy.py/pull/986

I realized this bug while adding integration tests for `modify_chunked_response` plugin.   They simply won't work for Python < 3.10.   Found the reason 🗡️ 

Above PR will fix it.  Can you give it a try.

Thank you for highlighting this issue to me.

**Comment by abhinavsingh** [comment]
> On the Mac I get this error message:
> File "...../proxy.py/proxy/common/flag.py", line 289, in initialize
> socket.AF_INET6 if args.hostname.version == 6 else socket.AF_INET
> AttributeError: 'str' object has no attribute 'version'

Did you use `hostname` as `ipaddress` or string?

When passing hostname as `kwargs`, it must be an `ipaddress` object.

> Windows again complains about _select:
> File "...Python\310\lib\selectors.py" line 315, in _select
> r, w, x = select.select(r, w, w, timeout)

What does it complain about?

**Comment by abhinavsingh** [comment]
Overall, I guess you are simply using it wrong.   I'll recommend you to look into existing code examples instead of hit and trial.  Example, browse the `examples` directory, which provided examples which use `proxy.py` in embedded mode.  Ref https://github.com/abhinavsingh/proxy.py/blob/develop/examples/https_connect_tunnel.py#L54-L70

At-least you can take inspiration about how your application main is going to look like.

**Comment by abhinavsingh** [comment]
Overall, now I am pretty sure no bug regarding TLS Interception exists, because now we have integration tests running across Python 3.6-3.10.  You can continue using any of supported Python versions if you wish.

**Comment by abhinavsingh** [comment]
I am not sure how are you running it.  Here are all possible default config methods.  All works fine.  I am on `develop` branch and on Mac (using Python 3.10).  I also verified the same steps on 3.9 too

<img width="1257" alt="Screen Shot 2022-01-14 at 7 24 21 PM" src="https://user-images.githubusercontent.com/126065/149526397-fa1516a6-1d60-40ec-9847-96515d1a7982.png">

Please check your setup.  Thank you!!!
